package com.ia.boot.project.Online.Admission.System;

import static org.assertj.core.api.Assertions.assertThat;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import com.ia.boot.project.OnlineAdmissionSystem.dao.CourseRepository;
import com.ia.boot.project.OnlineAdmissionSystem.model.Course;

class CourseRepoTest{
    @Autowired
    CourseRepository courseRepo;
    
    @BeforeEach
    void setUp() throws Exception {
        System.out.println("Setting Up..!!");
    }
    
    @Test
    void isExistsByCourseId() {
        Course courseForTest = new Course(100,"Test Course", "6 months" , 3, "C123");
        Course addedCourse= courseRepo.save(courseForTest);
        int courseIdAutoGenerated = addedCourse.getCourseId();
        
        assertThat(courseRepo.existsById(courseIdAutoGenerated)).isTrue();
    }
    
    @AfterEach
    void tearDown() throws Exception {
        System.out.println("Tearing Down");
        courseRepo.deleteAll();
    }
}